#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Tgxuserbot_REPO == "Tgx" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RvbjE5MDAvU2t5SGF3a3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $Tgxuserbot_REPO == "Tgx" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RvbjE5MDAvU2t5SGF3a3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $Tgxuserbot_REPO =~ $regex ]]
    then
        if [[ $Tgxuserbot_REPO_BRANCH ]]
        then
            echo "${Tgxuserbot_REPO}/archive/${Tgxuserbot_REPO_BRANCH}.zip"
        else
            echo "${Tgxuserbot_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RvbjE5MDAvU2t5SGF3a3VzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Tgx.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    TgxuserbotPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $TgxuserbotPATH
    echo "    Starting Tgx bot    "
    echo "
    ┈┈┈╲┈┈┈┈╱
┈┈╱▔▔▔▔╲
┈┈┃┈▇┈┈▇┈┃
╭╮┣━━━━━━┫╭╮
┃┃┃┈┈┈┈┈┈┃┃┃
╰╯┃┈┈┈┈┈┈┃╰╯
┈┈╰┓┏━━┓┏╯
┈┈┈╰╯┈┈╰╯


    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
